examples/basic.ipynb, examples/indexing.ipynb, examples/tensorwise.ipynb
Updated three examples: 
- basic
- indexing
- tensorwise
Changes:
[all] Different print out of expressions 
[all] Some renaming 
[indexing.ipynb] Removed unnecessary examples as they were duplicating the ones from basic.tpynb
[basic.ipynb] Moved sizes section next to dims section
=> Updated some examples

nestedtensor/version.py, test/utils_test_case.py
Added the layer of checks specifically for nested tensors. 
**TODO**
Uncomment `is_contiguous` check once the tests are updated.
=> Added nested tensor comparison layer for assertEqual

nestedtensor/csrc/nested_node.cpp, nestedtensor/csrc/nested_node.h, nestedtensor/version.py, test/test_nested_tensor_class.py
```
>>import torch
>>import nestedtensor
>>nt = nestedtensor.nested_tensor( 
[ 
[ 
torch.rand(2, 3), 
torch.rand(4, 5) 
], 
[ 
torch.rand(1, 2) 
] 
]) 
>>nt   
nested_tensor([
nested_tensor([
tensor([[0.5644, 0.5864, 0.5980],
[0.9558, 0.2837, 0.5108]]),
tensor([[0.5676, 0.4130, 0.8843, 0.7036, 0.0050],
[0.6556, 0.5470, 0.1995, 0.4825, 0.5201],
[0.8615, 0.5087, 0.9114, 0.1252, 0.0187],
[0.5486, 0.9834, 0.4116, 0.8418, 0.1067]])
]),
nested_tensor([
tensor([[0.6215, 0.3822]])
])
])
```
=> Pretty Print for NestedTensors

nestedtensor/csrc/nested_node.h, nestedtensor/csrc/nested_node_functions.h, nestedtensor/csrc/py_init.cpp, nestedtensor/csrc/python_nested_tensor.h, nestedtensor/nested/nested.py, nestedtensor/version.py, setup.py, test/test_nested_tensor_class.py
Introduce shape checking, all, any and generic THPIValueNode with comparison operation.
=> Fully move NestedTensor.nested_size/nested_stride into C++

benchmarks/unbind.py, benchmarks/utils.py, nestedtensor/csrc/nested_node.h, nestedtensor/csrc/python_nested_tensor.cpp, nestedtensor/csrc/python_nested_tensor.h, nestedtensor/version.py, setup.py
Benchmark for NestedTensor.unbind and slight perf improvements.
=> NestedTensor.unbind benchmark

nestedtensor/nested/codegen/extension.py, nestedtensor/nested/nested.py, nestedtensor/version.py
Landing in response to https://github.com/pytorch/pytorch/pull/34303
=> Adopt to new types argument for __torch_function__

nestedtensor/csrc/nested_tensor.cpp, nestedtensor/csrc/nested_tensor.h, nestedtensor/version.py, test/test_nested_tensor_autograd.py, test/test_nested_tensor_buffer.py, test/test_nested_tensor_class.py, test/test_nested_tensor_functional.py, test/test_nested_tensor_masking.py, test/test_nested_tensor_nary.py, test/test_nested_tensor_tensorwise.py, test/utils.py
Summary: See title.
Differential Revision: D20546180
=> 20200319 pytorch/nestedtensor import

.circleci/config.yml, nestedtensor/nested/functions.py, nestedtensor/nested/monkey_patch.py, nestedtensor/version.py, test/test_nested_tensor_functional.py, test/test_nested_tensor_integration.py
Enabled several nn functions to work with nested tensors.
Covered: 
- max_pool2d
- batch_norm
- relu
- interpolate
- cross_entropy
- dropout
Tested via unit tests
Todo: 
1. move the implementations to C++ for performance improvements.
=> functionals max_pool2d, batch_norm, relu, interpolate, cross_entropy, dropout

nestedtensor/csrc/unary.cpp
Fixes https://github.com/pytorch/nestedtensor/issues/87
=> Remove imag and real

benchmarks/segmentation_layers.py
- Fixed input generation
- Updated padding mechanism
- Fixed cross entropy for NT
=> Benchmark updates

benchmarks/segmentation_layers.py
- moved data generation before layer iteration to make the same input for layers 
- added ability to set various values for all args
=> Updated segmentation pipeline benchmark

benchmarks/segmentation_layers.py
- Creates explicit registration mechanism for Benchmarks, which also allows listing available benchmarks
- Parameterizes conv2d benchmark with kernel size by parsing parsed name
=> Suggested code-reorganization for segmentation pipeline benchmark

benchmarks/segmentation_layers.py
In/Out channels have to be either matched or separated into two different values but not hardcoded. 
Height, Width were calculated in the wrong way.
=> Update channels value and height/width calculation

nestedtensor/csrc/nested_tensor.h, nestedtensor/csrc/python_nested_tensor.cpp, nestedtensor/version.py
[This](https://github.com/pytorch/pytorch/commit/287f3b746eeb158a3766875f9564ae2505497bdf) commit broke us.
=> fixed build by adopting changes from pytorch

nestedtensor/csrc/functions.cpp, nestedtensor/csrc/functions.h, nestedtensor/csrc/python_functions.cpp, test/test_nested_tensor_functional.py
Updated interpolate with ability to work with list of sizes.
TODO: 
refactor and reuse code if possible
=> Updated interpolate to work with vector of sizes

nestedtensor/csrc/functions.cpp, nestedtensor/csrc/functions.h, nestedtensor/csrc/python_functions.cpp, nestedtensor/version.py, setup.py, test/test_nested_tensor_functional.py
Improved nested tensor performance by using passing by reference mechanisms. 
Tested via using local sripts and SLURM.
=> Improve functions performance by passing references

benchmarks/segmentation_layers.py, nestedtensor/csrc/functions.cpp, nestedtensor/csrc/functions.h, nestedtensor/csrc/python_nested_tensor.h, nestedtensor/version.py, test/test_nested_tensor_functional.py
TODO: Add more tests for contiguity
=> Perf updates for relu 

nestedtensor/csrc/BinaryOps.cpp, nestedtensor/csrc/creation.cpp, nestedtensor/csrc/functions.cpp, nestedtensor/csrc/nested_tensor_impl.cpp, nestedtensor/csrc/nested_tensor_impl.h, nestedtensor/csrc/py_init.cpp, nestedtensor/nested/nested.py, nestedtensor/version.py
Support multiplication and addition of a regular Tensor to a NestedTensor
=> torch.Tensor support for __mul__, __add__

nestedtensor/csrc/BinaryOps.cpp, nestedtensor/csrc/UnaryOps.cpp, nestedtensor/csrc/functions.cpp, nestedtensor/csrc/nested_tensor_impl.h, nestedtensor/csrc/utils/nested_node.h, nestedtensor/csrc/utils/nested_node_functions.h, nestedtensor/version.py
Adopts same API as map for apply
=> Improve NestedNode apply semantics

nestedtensor/csrc/nested_tensor_impl.cpp, nestedtensor/version.py, test/test_nested_tensor_autograd_functional.py, test/test_nested_tensor_functional.py
Adding autograd support for squeeze while removing squeeze(Tensor) and squeezing across nested dimensions for non-inplace ops.
=> Autograd for squeeze

nestedtensor/csrc/BinaryOps.cpp, nestedtensor/csrc/autograd_functions.cpp, nestedtensor/csrc/conv2d.cpp, nestedtensor/csrc/nested_tensor_impl.h, nestedtensor/csrc/utils/nested_node.h, nestedtensor/version.py, test/test_nested_tensor_nary.py
Now you can map across anything.
=> Improved map/apply semantics to support non-NT types.

.circleci/config.yml, .circleci/unittest/linux/scripts/environment.yml, .circleci/unittest/linux/scripts/install.sh, .circleci/unittest/linux/scripts/post_process.sh, .circleci/unittest/linux/scripts/run_test.sh, .circleci/unittest/linux/scripts/setup_env.sh
This reverts commit 52eecaf198ab056b6aeea08f6da7271e9cd4a68c , which is then used to fix the build issues.
=> Revert "Temporarily remove unit test builds. (#234)"

nestedtensor/version.py
Rebase pytorchfork nestedtensor branch on top of recent master
=> Rebase pytorch submodule

.circleci/unittest/linux/scripts/install.sh, .gitmodules
Updated [pytorch/nestedtensor branch](https://github.com/pytorch/pytorch/pull/47230) and rebuilding NT on top of it.
=> 20201102 Update PyTorch submodule

examples/README.md
Adds basic colab links. Changes required to run these examples on colab are to follow.
=> Colab links

.circleci/config.yml
=> .circleci: Add uploading step

.circleci/config.yml
Nightly versions weren't getting populated correctly so let's just
explicitly source
Another follow up to #279 
=> .circleci: Make sure env file gets sourced

.circleci/config.yml
=> .circleci: Use export for version vars

nestedtensor/csrc/Expand.cpp, nestedtensor/csrc/README.md, nestedtensor/csrc/ReduceOps.cpp, nestedtensor/csrc/autograd_functions.cpp, nestedtensor/csrc/nested_tensor_impl.cpp, nestedtensor/csrc/nested_tensor_impl.h, nestedtensor/nested/nested.py, nestedtensor/nn/mha.py, nestedtensor/version.py, test/test_nested_tensor_autograd_functional.py, test/test_nested_tensor_functional.py
Temporarily disables softmax backward
=> Explicitly disable NestedTensorImpl::sizes

.gitignore, build_with_submodule.sh
Fixes https://github.com/pytorch/nestedtensor/issues/314
=> Add build_with_submodule.sh

nestedtensor/csrc/BinaryOps.cpp, nestedtensor/csrc/ReduceOps.cpp, nestedtensor/version.py, test/test_coverage.py, test/test_nested_tensor_reduce.py
=> Check operator coverage (forward only) for issue 313

assets/NestedTensor_as_unifying_datastructure_for_non_uniform_Tensor_input.ipynb
Uploading an iPython notebook to support an upcoming RFC.
=> Add asset to support RFC post

.circleci/config.yml, .circleci/unittest/linux/scripts/install.sh, .circleci/unittest/linux/scripts/setup_env.sh, nestedtensor/csrc/UnaryOps.cpp, nestedtensor/version.py, test/test_nested_tensor_nary.py
Includes adoptions (such as reordering argument order (result vs. self) based on recent PyTorch changes) to reenable these ops.
=> Reenable Unary operations

nestedtensor/csrc/mha.cpp, nestedtensor/version.py, test/test_nested_tensor_autograd_functional.py, test/test_nested_tensor_functional.py, test/test_nested_tensor_reduce.py
Reenables reduction tests and the inference parts of a few functionals.
=> Reenable more tests

nestedtensor/nn/mha.py, nestedtensor/version.py, test/test_coverage.py, test/test_nested_tensor_autograd_functional.py, test/test_nested_tensor_class.py, test/test_nested_tensor_functional.py, test/test_nested_tensor_integration.py
This concludes all still applicable tests now that we're in inference mode only. Touches integration tests.
=> Reenable more tests - Part 2

nestedtensor/csrc/EmbeddingBag.cpp, nestedtensor/nested/nested.py, nestedtensor/version.py, test/test_nested_tensor_functional.py
=> Adopt embedding_bag to new changes

tutorials/notebooks/basic.ipynb
Includes changes to accommodate recent changes at a built against a PyTorch nightly (instead of a fork), which will make it much easier to install or possible at all.
=> Update Whirlwind tutorial

nestedtensor/version.py, packaging/build_wheel.sh, setup.py
Don't append the env variable, but use it to replace version entirely.
=> Change behavior of BUILD_VERSION env variable

nestedtensor/csrc/EmbeddingBag.cpp, nestedtensor/csrc/Expand.cpp, nestedtensor/csrc/ReduceOps.cpp, nestedtensor/csrc/nested_tensor_impl.h, nestedtensor/csrc/pooling.cpp, nestedtensor/csrc/python_functions.cpp, nestedtensor/version.py, test/test_nested_tensor_functional.py
Code cleanup and further modularization
=> Introduce reduce_/flatten_nested_tensor

nestedtensor/csrc/masking.cpp, nestedtensor/csrc/py_init.cpp, nestedtensor/nested/masking.py, nestedtensor/nested/nested.py, nestedtensor/version.py, test/test_nested_tensor_masking.py
Steps towards improving the performance of "to_tensor_mask" to a sane level.
=> Write padding code in C++

nestedtensor/nested/nested.py, nestedtensor/version.py
Converts NestedTensor into a [PackedSequence](https://pytorch.org/docs/master/generated/torch.nn.utils.rnn.pack_sequence.html?highlight=pack_sequence#torch.nn.utils.rnn.pack_sequence) for torch's RNNs.
=> to_packed_sequence

.circleci/config.yml, .circleci/unittest/linux/scripts/install.sh, nestedtensor/csrc/masking.cpp, nestedtensor/csrc/masking.h, nestedtensor/csrc/nested_tensor_impl.cpp, nestedtensor/nested/masking.py, nestedtensor/version.py
More steps towards efficiency and C++ support
=> Move get_max_size into C++

.circleci/config.yml, nestedtensor/csrc/EmbeddingBag.cpp, nestedtensor/csrc/Expand.cpp, nestedtensor/csrc/ReduceOps.cpp, nestedtensor/csrc/nested_tensor_impl.cpp, nestedtensor/csrc/nested_tensor_impl.h, nestedtensor/csrc/py_init.cpp, nestedtensor/csrc/utils/nested_node.h, nestedtensor/csrc/utils/python_nested_node.cpp, nestedtensor/csrc/utils/python_nested_node.h, nestedtensor/version.py
=> Replace c10::List<int64_t> with std::vector<int64_t>

nestedtensor/csrc/creation.cpp, nestedtensor/csrc/nested_tensor_impl.cpp, nestedtensor/csrc/nested_tensor_impl.h, nestedtensor/csrc/storage/Packed.h, nestedtensor/version.py, test/test_nested_tensor_masking.py
First steps towards abstracting the underlying memory layout and writing device-specific storage
=> Create explicit Packed Storage structure

nestedtensor/csrc/UnaryOps.cpp, nestedtensor/csrc/creation.cpp, nestedtensor/csrc/nested_tensor_impl.cpp, nestedtensor/csrc/nested_tensor_impl.h, nestedtensor/csrc/storage/List.h, nestedtensor/csrc/storage/Packed.h, nestedtensor/csrc/storage/Storage.h, nestedtensor/csrc/storage/common.h, nestedtensor/version.py, test/test_nested_tensor_masking.py
Together with List and Packed Storage this interface allows to switch between both in-memory representations and minimize overhead.
=> Create abstract NestedTensorStorage structure

nestedtensor/csrc/nested_tensor_impl.h, nestedtensor/csrc/storage/List.h, nestedtensor/csrc/storage/Packed.h, nestedtensor/csrc/storage/Storage.h, nestedtensor/csrc/utils/nested_node.h, nestedtensor/version.py, test/test_nested_tensor_masking.py
Reorder argument to infer return type of lambda. Cleans up the code a bit.
=> Improve reduce function

nestedtensor/csrc/cuda/transpose.cu, nestedtensor/csrc/transpose.cpp, nestedtensor/version.py
Reverts pytorch/nestedtensor#435
=> Revert "Use block oversubscription for transpose"

nestedtensor/__init__.py, nestedtensor/nested/fuser.py, nestedtensor/version.py, test/test_nested_tensor_integration.py
Still doesn't fuse all Modules, but already a vast majority. To see real gains this needs at least cudnn8.2 (at least for fp16) and channels last input.
=> FX based fuser for Conv2d and ReLU

nestedtensor/csrc/UnaryOps.cpp
=> also fix clamp_max_out

.circleci/unittest/linux/scripts/install.sh, nestedtensor/csrc/python_functions.cpp, test/test_nested_tensor_functional.py
Interpolate has a new argument and we should support it.
=> Support new interpolate argument

nestedtensor/csrc/cuda/padding.cu, nestedtensor/csrc/cuda/padding.h, nestedtensor/csrc/functions.cpp, nestedtensor/csrc/masking.cpp, nestedtensor/csrc/nested_tensor_impl.cpp, nestedtensor/csrc/nested_tensor_impl.h, nestedtensor/csrc/storage/EfficientSizeNode.h, nestedtensor/csrc/transpose.cpp, nestedtensor/version.py
Use TensorImpl dtype and device
Remove _height from EfficientSizeNode
Collapse dims before adding padding
=> Small optimizations for MHA
