pytorch/nestedtensor

- setup.py
Without the flag I got this issue when running setup.py. 
```
(nightly) justanhduc@insight-SIM3:~/Downloads/nestedtensor$ python setup.py develop
Building wheel nestedtensor-0.0.1.dev20201102+1643992
running develop
running egg_info
creating nestedtensor.egg-info
writing nestedtensor.egg-info/PKG-INFO
writing dependency_links to nestedtensor.egg-info/dependency_links.txt
writing requirements to nestedtensor.egg-info/requires.txt
writing top-level names to nestedtensor.egg-info/top_level.txt
writing manifest file 'nestedtensor.egg-info/SOURCES.txt'
reading manifest file 'nestedtensor.egg-info/SOURCES.txt'
writing manifest file 'nestedtensor.egg-info/SOURCES.txt'
running build_ext
building 'nestedtensor._C' extension
creating build
creating build/temp.linux-x86_64-3.7
creating …
```
> Added flag '-std=c++14' to CXX

- nestedtensor/version.py
- test/test_nested_tensor_nary.py
- test/utils_test_case.py
We need to add `ignore_contiguity` flag due to difference in constructors behavior.
> Enabled contiguity check in assertEqual

- nestedtensor/nested/masking.py
- nestedtensor/version.py
- test/test_nested_tensor_masking.py
- test/utils.py
Methods covered:
- gen_nested_tensor
- to_tensor_mask
- nested_tensor_from_tensor_mask
ToDo:
- cover edge cases
- cover error cases
> Added basic test coverage for nested tensor masking

- nestedtensor/csrc/unary.cpp
See related https://github.com/pytorch/pytorch/pull/35560. NumPy doesn't offer out variants of these functions, nor do we offer an out argument for contiguous, which, like real, can return self. Other functions that return views (like diagonal) also don't support out=. We can work out a plan to add back NestedTensor support for them later, but we'd like to cherrypick the real/imag fix for 1.5, so there's some urgency to this change.
> Removes imag_out and real_out

- nestedtensor/csrc/functions.cpp
- nestedtensor/csrc/functions.h
- nestedtensor/csrc/python_args.h
- nestedtensor/csrc/python_functions.cpp
- nestedtensor/version.py
- test/test_nested_tensor_functional.py
For interpolate and conv2d there are arguments that can be passed as a single value or a tuple. This PR enables this behavior for NT.
> Updated overloads for interpolate and conv2d to expect different arguments.

- benchmarks/segmentation_layers.py
- benchmarks/utils.py
- nestedtensor/version.py
Added benchmarking for segmentation pipeline layers. 
Example of usage: 
`>>> clear && python benchmarks/segmentation_layers.py -L relu_tensor_pad relu_nt -N 10 -C 3 -W 100 -H 100 -HV 10 11 -WV 10  11 -S 24 -WARM 0.0`
```
<<<
called with:  Namespace(C=3, H=100, HV=[10, 11], N=10, W=100, WV=[10, 11], layers=['relu_tensor_pad', 'relu_nt'], seed=[24], warm=0.0)
_relu_tensor_pad , 505.16448974609375 , 23.60953140258789 , 9898 , 10 , 10 , 24
_relu_nt , 526.1130981445312 , 18.652135848999023 , 9504 , 10 , 10 , 24
_relu_tensor_pad , 493.748779296875 , 15.7689847946167 , 10127 , 10 , 11 , 24
_relu_nt , 526.4400634765625 , 29.80328941345215 , 9498 , 10 , 11 , 24
_relu_tensor_pad , 481.2615051269531 , 21.609426498413086 , 10390 , 11 , 10 , 24
_relu_nt , 580.851806640625 , 42.515838623046875 , 8609 …
```
> initial benchmarking for segmentation pipeline 

- benchmarks/segmentation_layers.py
Few changes I missed...
```
(source) ➜  nestedtensor git:(up3) ✗ python benchmarks/segmentation_layers.py -L conv2d_nt_1x1 conv2d_iter_3x3 relu_tensor_pad batch_norm_tensor_iter max_pool2d_nt -N 20 -C 3 -H 100 -W 100 -HV 0 10 -WV 0 -S 24 -WARM 2
('C', 3),('H', 100),('N', 20),('W', 100),('avg_us', 28559),('h_var', 0),('name', 'conv2d_nt_1x1'),('runs', 176),('seed', 24),('std_us', 4113),('w_var', 0)
('C', 3),('H', 100),('N', 20),('W', 100),('avg_us', 21018),('h_var', 0),('name', 'conv2d_iter_3x3'),('runs', 238),('seed', 24),('std_us', 2216),('w_var', 0)
('C', 3),('H', 100),('N', 20),('W', 100),('avg_us', 887),('h_var', 0),('name', 'relu_tensor_pad'),('runs', 5632),('seed', 24),('std_us', 176),('w_var', 0)
('C', 3),('H', 100),('N', 20),('W', 100),('avg_us', 1398),('h_var', 0),('name', …
```
> Segmentation benchmark follow-up fixes

- benchmarks/segmentation_layers.py
- nestedtensor/csrc/functions.cpp
- nestedtensor/version.py
Benchmark argument:
```
python benchmarks/segmentation_layers.py \
-L relu_tensor_iter relu_nt relu_tensor_pad \
-N 20 -C 256 512 -H 80 -W 80 -V 0 5 10 -S 24
```
> Implement relu for cont. NestedTensor input

- nestedtensor/csrc/creation.cpp
- nestedtensor/csrc/creation.h
- nestedtensor/csrc/functions.cpp
- nestedtensor/csrc/py_init.cpp
- nestedtensor/nested/creation.py
- nestedtensor/version.py
- test/test_nested_tensor_autograd.py
- test/test_nested_tensor_class.py
- test/test_nested_tensor_functional.py
Resolves issue https://github.com/pytorch/nestedtensor/issues/150
as_nested_tensor now forwards NestedTensors only. This gets rid of the current view semantics of as_nested_tensor.
> Change as_nested_tensor to only forward NestedTensor type

- benchmarks/segmentation_layers.py
Fixed a bug with not passing cuda argument to benchmarks.
> Fixed cuda sync

- nestedtensor/csrc/ReduceOps.cpp
- nestedtensor/version.py
- test/test_nested_tensor_reduce.py
This doesn't support all the craziness like reducing the nested dimension by 1
when reducing at the nested dimension, and being able to reduce before the nested
dimension with lists if you reduce across the nested dimension.
It simply allows users to reduce across the nested dimension or higher.
> Add support for sum.dim_IntList and mean.dim

- nestedtensor/csrc/ReduceOps.cpp
- nestedtensor/csrc/creation.cpp
- nestedtensor/csrc/creation.h
- nestedtensor/nested/creation.py
- nestedtensor/nested/nested.py
- nestedtensor/version.py
- test/test_nested_tensor_autograd.py
- test/test_nested_tensor_class.py
- test/test_nested_tensor_functional.py
- test/test_nested_tensor_nary.py
to was implemented very inefficient and requires a lot of overloads. current usesites don't require ".to" other than for construction. we'll disable it for now until we need it again and then reimplement it as a native function.
> Add dtype, device, requires_grad and pin_memory to constructor, disable NestedTensor.to

- .circleci/config.yml
Was uploading as the actual subfolder instead of as an item under the
subfolder
This is a follow up to #279 
> .circleci: Fix upload step to upload to subdir

- .circleci/config.yml
> .circleci: Use CIRCLE_BRANCH instead of pipelin.git.branch

- nestedtensor/nn/parameter.py
I've written custom parsers and emitters for everything from docstrings to classes and functions. However, I recently came across an issue when I was parsing/generating from the TensorFlow—and now PyTorch—codebases: inconsistent use of `Args:` and `Arguments:` in its docstrings. It is easy enough to extend my parsers to support both variants, however it looks like `Arguments:` is wrong anyway, as per:
- https://google.github.io/styleguide/pyguide.html#doc-function-args @ [`ddccc0f`](https://github.com/google/styleguide/blob/ddccc0f/pyguide.md)
- https://chromium.googlesource.com/chromiumos/docs/+/master/styleguide/python.md#describing-arguments-in-docstrings @ [`9fc0fc0`](https://chromium.googlesource.com/chromiumos/docs/+/9fc0fc0/styleguide/python.md)
- …
> [*.py] Rename "Arguments:" to "Args:"

- .circleci/unittest/linux/scripts/install.sh
- nestedtensor/csrc/BinaryOps.cpp
- nestedtensor/csrc/ComparisonOps.cpp
- nestedtensor/csrc/EmbeddingBag.cpp
- nestedtensor/csrc/creation.cpp
- nestedtensor/csrc/scripts/binaryops.py
- nestedtensor/version.py
- test/test_nested_tensor_nary.py
- test/utils.py
Missing all the pow variants and ```Scalar other``` overloads.
> Bring back add, div, mul, sub, remainder, atan2

- .circleci/unittest/linux/scripts/install.sh
- nestedtensor/csrc/py_init.cpp
- nestedtensor/version.py
- test/test_nested_tensor_functional.py
This guard will disable autograd for anyone who is even just importing nestedtensor. It's a temporary hack until the inferencemode python guard becomes available.
> Add static inference guard

- nestedtensor/csrc/creation.cpp
- nestedtensor/version.py
- test/test_nested_tensor_class.py
- test/test_nested_tensor_functional.py
- test/test_nested_tensor_masking.py
- test/test_nested_tensor_nary.py
- test/test_nested_tensor_reduce.py
In context of focus on inference this restricts various use cases, but also makes it easier to write efficient kernels.
> Restrict nested dim to one - tests and constructor

- .circleci/unittest/linux/scripts/install.sh
- benchmarks/classy.py
- benchmarks/conv2d.py
- nestedtensor/csrc/BinaryOps.cpp
- nestedtensor/csrc/activation.cpp
- nestedtensor/csrc/autograd_functions.cpp
- nestedtensor/csrc/conv2d.cpp
- nestedtensor/csrc/cuda/add.cu
- nestedtensor/csrc/cuda/add.h
- nestedtensor/csrc/masking.cpp
- nestedtensor/csrc/nested_tensor_impl.cpp
- nestedtensor/csrc/nested_tensor_impl.h
- nestedtensor/csrc/shape.cpp
- nestedtensor/csrc/storage/EfficientSizeNode.h
- nestedtensor/csrc/storage/Packed.h
- nestedtensor/csrc/utils/nested_node.h
- nestedtensor/version.py
- test/test_coverage.py
- test/test_nested_tensor_functional.py
Includes CUDA kernels for
- add
- mul
- sub
- batchnorm forward
Various metadata improvements by spreading the use of EfficientSizeNode and specializing on nested_dim == 1
Improved treatment of contiguous memory for
- 1x1 conv2d
- relu_
```
model_name:   resnext101_32x4d, bsz: 64, mean±std shapes[2]: 323.17±145.32, mean±std shapes[3]: 363.86±141.50, loop: 1.54s, nt: 0.50s, speedup: 3.09x
model_name:   resnext101_32x4d, bsz: 128, mean±std shapes[2]: 319.36±143.50, mean±std shapes[3]: 361.93±141.42, loop: 3.09s, nt: 0.98s, speedup: 3.14x
model_name:   resnext101_32x4d, bsz: 256, mean±std shapes[2]: 334.34±147.87, mean±std shapes[3]: 365.12±139.76, loop: 6.33s, nt: 2.18s, speedup: 2.91x
```
> resnext101_32x4d oriented optimized implementations for packed memory.

- benchmarks/classy.py
- nestedtensor/csrc/cuda/padding.cu
- nestedtensor/csrc/cuda/padding.h
- nestedtensor/csrc/masking.cpp
- nestedtensor/version.py
- test/test_nested_tensor_class.py
Master
```
model_name:   resnext101_32x4d, bsz:  16, mean±std shapes[2]: 256.75±135.80, mean±std shapes[3]: 370.56±148.10, padded_size: (16, 3, 561, 563), loop:  364.19ms, nt:   98.25ms, padded:  113.14ms, speedup: 3.71x
model_name:   resnext101_32x4d, bsz:  32, mean±std shapes[2]: 304.19±155.05, mean±std shapes[3]: 330.72±145.72, padded_size: (32, 3, 566, 564), loop:  740.61ms, nt:  157.64ms, padded:  199.59ms, speedup: 4.70x
model_name:   resnext101_32x4d, bsz:  64, mean±std shapes[2]: 323.17±145.32, mean±std shapes[3]: 363.86±141.50, padded_size: (64, 3, 567, 591), loop: 1481.89ms, nt:  324.53ms, padded:  410.88ms, speedup: 4.57x
model_name:   resnext101_32x4d, bsz: 128, mean±std shapes[2]: 319.36±143.50, mean±std shapes[3]: 361.93±141.42, padded_size: (128, 3, 593, 599), loop: …
```
> Faster padding - fuse fill, reduce overhead

- benchmarks/classy.py
- nestedtensor/csrc/autograd_functions.cpp
- nestedtensor/csrc/cuda/add.cu
- nestedtensor/csrc/cuda/transpose.cu
- nestedtensor/version.py
In-place calculation and more blocks.
Master
```
model_name:   resnext101_32x4d, bsz:  16, mean±std shapes[2]: 256.75±135.80, mean±std shapes[3]: 370.56±148.10, padded_size: (16, 3, 561, 563), loop:  368.53ms, nt:   94.62ms, padded:  113.88ms, speedup: 3.89x
model_name:   resnext101_32x4d, bsz:  32, mean±std shapes[2]: 304.19±155.05, mean±std shapes[3]: 330.72±145.72, padded_size: (32, 3, 566, 564), loop:  751.15ms, nt:  152.72ms, padded:  199.85ms, speedup: 4.92x
model_name:   resnext101_32x4d, bsz:  64, mean±std shapes[2]: 323.17±145.32, mean±std shapes[3]: 363.86±141.50, padded_size: (64, 3, 567, 591), loop: 1502.62ms, nt:  309.38ms, padded:  409.75ms, speedup: 4.86x
model_name:   resnext101_32x4d, bsz: 128, mean±std shapes[2]: 319.36±143.50, mean±std shapes[3]: 361.93±141.42, …
```
> Faster batchnorm inference
